name: hundred_days_of_programming
version: 1.0.0+1
publish_to: none
description: This app is designed for beginners eager to learn programming through a 100-day coding challenge. It offers 100 problem statements, ranging from very basic to intermediate levels. Users will solve these problems, submit their solutions on GitHub and LinkedIn, and provide the URLs in the app for verification. Once verified, the tasks will be marked as complete.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cloud_firestore: 5.1.0
  cupertino_icons: 1.0.8
  firebase_analytics: 11.2.0
  firebase_auth: 5.1.2
  firebase_core: 3.2.0
  firebase_crashlytics: 4.0.3
  flutter_dotenv: 5.1.0
  google_fonts: 6.2.1
  markdown_widget: 2.3.2+6
  get: 4.6.6
  intl: 0.19.0
  url_launcher: 6.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: ic_launcher
  image_path: assets/icon/icon.png
  ios: true

flutter: 
  assets: 
    - assets/icon/icon.png
    - assets/image/cold_streak.png
    - assets/image/hot_streak.png
    - .env
  uses-material-design: true

